#
# diosix's CI script
#
# Due to Travis CI constraints, this script just checks the RV64GC target builds and passes tests
#
dist: xenial
sudo: required
language: rust
rust:
  - nightly
cache: cargo
notifications:
  email: false

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install flex bison m4 sed texinfo git
  #
  # build the GNU binary tools
  #
  - mkdir -p $HOME/cross
  - git clone -q -b riscv-binutils-2.32 https://github.com/riscv/riscv-binutils-gdb.git
  - cd riscv-binutils-gdb
  - ./configure -q --prefix $HOME/cross --target=riscv64-elf
  - make -s
  - make -s install
  - export PATH=$PATH:$HOME/cross/bin
  #
  # build qemu to run the tests
  #
  - cd $HOME
  - sudo apt-get -qq install libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev
  - git clone -q -b master https://github.com/qemu/qemu.git
  - cd qemu
  - ./configure --target-list=riscv64-softmmu
  - make -s
  - export PATH=$PATH:$HOME/qemu/riscv64-softmmu
  #
  # build linux using buildroot for the hypervior to boot
  #
  - cd $HOME
  - git clone https://github.com/buildroot/buildroot.git
  - cd buildroot
  # 
  # build riscv64gc
  #
  - cp $TRAVIS_BUILD_DIR/boot/buildroot/riscv64gc.config .config
  - make -s
  - mkdir -p $TRAVIS_BUILD_DIR/boot/binaries/riscv64gc/
  - cp output/images/vmlinux $TRAVIS_BUILD_DIR/boot/binaries/riscv64gc/supervisor
  #
  # return to diosix
  #
  - cd $TRAVIS_BUILD_DIR

before_script:
  - rustup target install riscv64gc-unknown-none-elf

script:
  - cargo test --release --target riscv64gc-unknown-none-elf

branches:
  only:
    - master
