#
# diosix's CI script
#
dist: xenial
sudo: required
language: rust
rust:
  - nightly
cache: cargo
notifications:
  email: false

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install flex bison m4 sed texinfo
  - mkdir $HOME/cross
  - git clone -b riscv-binutils-2.32 https://github.com/riscv/riscv-binutils-gdb.git
  - cd riscv-binutils-gdb
  - ./configure --prefix $HOME/cross --target=riscv32-elf
  - make
  - make install
  - make clean
  - find . -type f -name "config.cache" -exec rm {} \;
  - ./configure --prefix $HOME/cross --target=riscv64-elf
  - make
  - make install
  - export PATH=$PATH:$HOME/cross/bin
  - cd $HOME
  - sudo apt-get -qq install git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev
  - git clone -b master https://github.com/qemu/qemu.git
  - cd qemu
  - ./configure --target-list=riscv32-softmmu,riscv64-softmmu
  - make
  - export PATH=$PATH:$HOME/qemu/riscv32-softmmu/qemu-system-riscv32
  - export PATH=$PATH:$HOME/qemu/riscv64-softmmu/qemu-system-riscv64

before_script:
  rustup target install riscv32imac-unknown-none-elf
  rustup target install riscv64imac-unknown-none-elf
  rustup target install riscv64gc-unknown-none-elf

script:
  - cargo build --release --target riscv32imac-unknown-none-elf
  - cargo build --release --target riscv64imac-unknown-none-elf
  - cargo build --release --target riscv64gc-unknown-none-elf
  - cargo test --release --target riscv32imac-unknown-none-elf
  - cargo test --release --target riscv64imac-unknown-none-elf
  - cargo test --release --target riscv64gc-unknown-none-elf

branches:
  only:
    - master
