#
# diosix's CI script
#
dist: trusty
sudo: required
language: rust
rust:
  - nightly
cache: cargo

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install flex bison m4 sed texinfo
  - mkdir $HOME/cross
  - git clone -b riscv-binutils-2.30 https://github.com/riscv/riscv-binutils-gdb.git
  - cd riscv-binutils-gdb
  - ./configure --prefix $HOME/cross --target=riscv32-elf
  - make
  - make install
  - export PATH=$PATH:$HOME/cross/bin
  - cd ..

before_script:
  rustup target install riscv32imac-unknown-none-elf

script:
  - ./build.sh --triple riscv32imac-unknown-none-elf --platform sifive_u34
  - ./build.sh --triple riscv32imac-unknown-none-elf --platform qemu_virt

branches:
  only:
    - master
