// diosix build management
//
// Don't invoke this file directly. Instead use the wrapper `./scripts/build.sh`.
// This wrapper ensures that all necessary build-time metadata is freshly captured
// and passed to the build automatically.
//
// Copyright (c) 2024, 2025, 2026 Chris Williams <chrisw@diosix.org>
// SPDX-License-Identifier: MIT

const std = @import("std");
const ArrayList = std.ArrayList;
const Target = std.Target;
const RISCVextensions = Target.Cpu.Feature.Set;

pub fn build(b: *std.Build) !void {
    const git_branch = b.option([]const u8, "git_branch", "Current git branch") orelse "unknown branch";
    const git_revision = b.option([]const u8, "git_revision", "Current git revision") orelse "unknown revision";
    const zig_version_opt = b.option([]const u8, "zig_version", "Current zig version") orelse "unknown zig version";
    const build_user = b.option([]const u8, "build_user", "Current build user") orelse "unknown build user";
    const build_hostname = b.option([]const u8, "build_hostname", "Current build hostname") orelse "unknown build host";
    const build_date = b.option([]const u8, "build_date", "Current build date") orelse "unknown build date";

    const qemu_cpu_opt = b.option([]const u8, "qemu-cpu", "Override the CPU model/extensions passed to QEMU");
    const legacy_cpu = b.option(bool, "legacy-cpu", "Compile out Sstc and Smstateen support") orelse false;
    const pmp_fallback = b.option(bool, "pmp", "Run in PMP fallback mode (disable H-extension)") orelse false;
    const smp_cores = b.option(u32, "smp", "Number of SMP CPU cores for emulator") orelse 4;
    const mem_size = b.option([]const u8, "mem", "Memory size for emulator (e.g. 2G)") orelse "2G";

    // Generate config.s dynamically
    const config_s_content = try std.fmt.allocPrint(b.allocator,
        \\# Dynamically generated by build.zig. DO NOT EDIT.
        \\.equ LEGACY_CPU, {d}
        \\
    , .{@intFromBool(legacy_cpu)});

    // we're building primarily for riscv64 systems, and expect RV64IMAC as a minimum.
    // override zig's CPU extension list with our own.
    var min_cpu_features = RISCVextensions.empty;
    const i: std.Target.riscv.Feature = .i;
    const m: std.Target.riscv.Feature = .m;
    const a: std.Target.riscv.Feature = .a;
    const c: std.Target.riscv.Feature = .c;
    const h: std.Target.riscv.Feature = .h;
    min_cpu_features.addFeature(@intFromEnum(i));
    min_cpu_features.addFeature(@intFromEnum(m));
    min_cpu_features.addFeature(@intFromEnum(a));
    min_cpu_features.addFeature(@intFromEnum(c));
    min_cpu_features.addFeature(@intFromEnum(h));

    // insist on building for riscv64 targets
    const target = b.standardTargetOptions(.{
        .default_target = .{
            .cpu_arch = Target.Cpu.Arch.riscv64,
            .os_tag = Target.Os.Tag.freestanding,
            .abi = Target.Abi.none,
            .cpu_model = .{ .explicit = &Target.riscv.cpu.baseline_rv64 },
            .cpu_features_add = min_cpu_features,
        },
    });

    // allow user to control or override optimizations and release mode
    const optimize = b.standardOptimizeOption(.{});

    const interface_module = b.createModule(.{
        .root_source_file = b.path("hypervisor/interface/lib.zig"),
    });

    // Allow user to select the guest Root VM architecture
    const guest_arch_opt = b.option([]const u8, "guest-arch", "Select the guest architecture to build for: riscv64, riscv32, aarch64, aarch32, x86_64, mips, mips64, ppc") orelse "riscv64";

    const config_filename = try std.fmt.allocPrint(b.allocator, "boot/{s}-linux-busybox-micropython.config", .{guest_arch_opt});
    defer b.allocator.free(config_filename);

    const rootvm_elf_path = b.fmt("zig-out/guest-{s}/bin/rootvm.elf", .{guest_arch_opt});
    const buildroot_dir = b.fmt("zig-out/buildroot-{s}", .{guest_arch_opt});

    const run_buildroot = b.addSystemCommand(&.{ "bash", "scripts/build_rootvm.sh" });
    run_buildroot.addFileArg(b.path(config_filename));
    run_buildroot.addArg(rootvm_elf_path);
    run_buildroot.addArg(buildroot_dir);
    run_buildroot.addArg(guest_arch_opt);


    const emulation_module = b.createModule(.{
        .root_source_file = b.path("hypervisor/hardware/emulation/mod.zig"),
    });

    const vmdiosix = b.addExecutable(.{ .name = "vmdiosix", .root_module = b.createModule(.{
        .root_source_file = b.path("hypervisor/main.zig"),
        .optimize = optimize,
        .target = target,
        .code_model = .medium,
    }), .linkage = .static });
    vmdiosix.step.dependOn(&run_buildroot.step);
    vmdiosix.root_module.addImport("interface", interface_module);
    vmdiosix.root_module.addImport("emulation", emulation_module);


    // Dynamically read the modification hash of the rootvm.elf payload if it exists
    var current_hash: []const u8 = "unknown";
    const hash_file_path = b.fmt("zig-out/guest-{s}/bin/rootvm.elf.sha256", .{guest_arch_opt});
    if (b.root.root_dir.handle.readFileAlloc(b.graph.io, hash_file_path, b.allocator, std.Io.Limit.limited(1024))) |content| {
        current_hash = std.mem.trim(u8, content, " \t\r\n");
    } else |_| {}

    const rootvm_elf_abs_path = try b.root.joinString(b.allocator, rootvm_elf_path);
    const rootvm_s_content = try std.fmt.allocPrint(b.allocator,
        \\# Dynamically generated by build.zig. DO NOT EDIT.
        \\# Modification hash: {s}
        \\.section .rootvm, "a"
        \\.global root_vm_start
        \\.global root_vm_end
        \\.balign 4096
        \\root_vm_start:
        \\.incbin "{s}"
        \\root_vm_end:
        \\
    , .{ current_hash, rootvm_elf_abs_path });

    const rootvm_s_step = b.addWriteFiles();
    const rootvm_s_file = rootvm_s_step.add("rootvm.s", rootvm_s_content);

    // include the assembly files and linker script
    const assembly_files = [_][]const u8{
        "hypervisor/hardware/native/cpu/riscv64/entry.s",
        "hypervisor/hardware/native/cpu/riscv64/xint.s",
        "hypervisor/hardware/native/cpu/riscv64/util.s",
    };
    for (assembly_files) |asm_file| {
        vmdiosix.root_module.addAssemblyFile(b.path(asm_file));
    }
    vmdiosix.root_module.addAssemblyFile(rootvm_s_file);
    vmdiosix.step.dependOn(&rootvm_s_step.step);

    vmdiosix.setLinkerScript(b.path("hypervisor/hardware/native/cpu/riscv64/linker.ld"));

    // Register all dependencies (like consts.s) so modifying any of them triggers a full rebuild
    var dep_step = b.addWriteFiles();
    const filename = "consts.s";
    _ = dep_step.addCopyFile(b.path("hypervisor/hardware/native/cpu/riscv64/consts.s"), filename);
    vmdiosix.root_module.addIncludePath(dep_step.getDirectory());
    vmdiosix.step.dependOn(&dep_step.step);

    // include build-time config options
    const driver_ns16550 = b.option(bool, "driver-ns16550", "Compile in NS16550 UART driver") orelse true;
    const driver_clint = b.option(bool, "driver-clint", "Compile in CLINT timer driver") orelse true;
    const driver_sifive_test = b.option(bool, "driver-sifive-test", "Compile in SiFive test device driver") orelse true;
    const enable_gdb = b.option(bool, "gdb", "Enable embedded GDB RSP remote debugging stub") orelse false;

    const hypervisor_options = b.addOptions();
    hypervisor_options.addOption(bool, "legacy_cpu", legacy_cpu);
    hypervisor_options.addOption(bool, "compile_ns16550", driver_ns16550);
    hypervisor_options.addOption(bool, "compile_clint", driver_clint);
    hypervisor_options.addOption(bool, "compile_sifive_test", driver_sifive_test);
    hypervisor_options.addOption(bool, "enable_gdb", enable_gdb);
    vmdiosix.root_module.addOptions("config", hypervisor_options);

    // Generate config.s dynamically inside the build cache
    const config_step = b.addWriteFiles();
    _ = config_step.add("config.s", config_s_content);
    vmdiosix.root_module.addIncludePath(config_step.getDirectory());
    vmdiosix.step.dependOn(&config_step.step);

    // include build-time metadata as options available to main.zig
    // this includes boot banner text, and details of the build and current version
    const metadata = b.addOptions();

    metadata.addOption([]const u8, "banner", @embedFile("boot/banner.txt"));
    metadata.addOption([]const u8, "project_version", @embedFile("VERSION"));
    metadata.addOption([]const u8, "git_branch", git_branch);
    metadata.addOption([]const u8, "git_revision", git_revision);
    metadata.addOption([]const u8, "build_date", build_date);
    metadata.addOption([]const u8, "build_user", build_user);
    metadata.addOption([]const u8, "build_hostname", build_hostname);
    metadata.addOption([]const u8, "zig_version", zig_version_opt);
    metadata.addOption([]const u8, "cpu_arch", "riscv64");

    // Compile the metadata object file separately to decouple options invalidation.
    // This holds the versioning strings and is linked to the main executable.
    const metadata_obj = b.addObject(.{
        .name = "metadata_info",
        .root_module = b.createModule(.{
            .root_source_file = b.path("hypervisor/core/metadata.zig"),
            .optimize = optimize,
            .target = target,
        }),
    });
    metadata_obj.root_module.addOptions("metadata", metadata);
    vmdiosix.root_module.addObjectFile(metadata_obj.getEmittedBin());

    const install_step = b.addInstallArtifact(vmdiosix, .{
        .dest_dir = .{ .override = .{ .custom = b.fmt("guest-{s}/bin", .{guest_arch_opt}) } }
    });
    b.getInstallStep().dependOn(&install_step.step);

    // create a 'zig build run' command to execute the hypervisor in a suitable emulator
    var qemu_args = ArrayList([]const u8).empty;
    defer qemu_args.deinit(b.allocator);

    try qemu_args.append(b.allocator, "qemu-system-riscv64");
    try qemu_args.append(b.allocator, "-gdb");
    try qemu_args.append(b.allocator, "tcp::12345");
    if (enable_gdb) {
        try qemu_args.append(b.allocator, "-serial");
        try qemu_args.append(b.allocator, "tcp::1234,server,nowait");
    } else {
        try qemu_args.append(b.allocator, "-nographic");
    }
    try qemu_args.append(b.allocator, "-machine");
    try qemu_args.append(b.allocator, "virt");
    try qemu_args.append(b.allocator, "-cpu");
    if (qemu_cpu_opt) |cpu| {
        try qemu_args.append(b.allocator, cpu);
    } else {
        var cpu_buf = ArrayList(u8).empty;
        defer cpu_buf.deinit(b.allocator);
        try cpu_buf.appendSlice(b.allocator, "rv64");
        if (pmp_fallback) {
            try cpu_buf.appendSlice(b.allocator, ",h=false");
        } else {
            try cpu_buf.appendSlice(b.allocator, ",h=true");
        }
        if (legacy_cpu) {
            try cpu_buf.appendSlice(b.allocator, ",smstateen=false,sstc=false");
        } else {
            try cpu_buf.appendSlice(b.allocator, ",smstateen=true,sstc=true");
        }
        try cpu_buf.appendSlice(b.allocator, ",v=true");
        try qemu_args.append(b.allocator, try cpu_buf.toOwnedSlice(b.allocator));
    }
    try qemu_args.append(b.allocator, "-smp");
    try qemu_args.append(b.allocator, b.fmt("{d}", .{smp_cores}));
    try qemu_args.append(b.allocator, "-m");
    try qemu_args.append(b.allocator, mem_size);
    try qemu_args.append(b.allocator, "-bios");
    try qemu_args.append(b.allocator, "none");
    try qemu_args.append(b.allocator, "-kernel");

    const run_step = b.addSystemCommand(qemu_args.items);
    run_step.step.dependOn(b.getInstallStep());

    // the last argument to qemu is the kernel file to run
    run_step.addArtifactArg(vmdiosix);
    run_step.stdio = .inherit;

    const run_option = b.step("run", "Run the hypervisor");
    run_option.dependOn(&run_step.step);

    // run all the unit tests on the host system
    // tests use a separate module targeting native so the test runner has OS support
    const test_module = b.createModule(.{
        .root_source_file = b.path("hypervisor/main.zig"),
        .optimize = optimize,
        .target = b.graph.host,
    });
    test_module.addImport("interface", interface_module);
    test_module.addImport("emulation", emulation_module);
    test_module.addOptions("config", hypervisor_options);
    const unit_tests = b.addTest(.{
        .root_module = test_module,
        .name = "diosix-unit-tests",
    });

    // Compile and link the metadata info separately for host unit tests
    const test_metadata_obj = b.addObject(.{
        .name = "metadata_info_test",
        .root_module = b.createModule(.{
            .root_source_file = b.path("hypervisor/core/metadata.zig"),
            .optimize = optimize,
            .target = b.graph.host,
        }),
    });
    test_metadata_obj.root_module.addOptions("metadata", metadata);
    unit_tests.root_module.addObjectFile(test_metadata_obj.getEmittedBin());

    const run_unit_tests = b.addRunArtifact(unit_tests);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_unit_tests.step);
}
