# Define the contents of a base system the hypervisor can boot
#
# This base system contains welcome banner(s), system services,
# and guests OSes that are bundled with the hypervisor binary
# and unpacked at run-time
#
# See src/mkdmfs/src/main.rs for the file format
#
# Directory paths are relative to this manifest.toml file

# these can be overridden by whatever's parsing this file, usually mkdmfs
[defaults]
arch = "riscv64gc-unknown-none-elf"
quality = "debug"
outfile = "src/mkdmfs/target/dmfs.img"

# define where to find the welcome banners
[banners]
path = "boot/banners"
welcome = "boot/banners/welcome.txt"

# define system services to include
[services]
include = [ "gooey" ]

# define each individual service
[service.gooey]
path = "src/services"
description = "console interface"
properties = [ "auto_crash_restart", "service_console", "console_write", "console_read", "hv_log_read" ]

# define each guest that may join us during boot
# Mildly useful Linux with busybox, micropython, zsh, and less
[guest.riscv64-linux-busybox-micropython]
path = "boot/guests"
url = "https://github.com/diodesign/diosix/raw/binaries/buildroot-guests/riscv64-linux-busybox-micropython"
description = "64-bit RISC-V Linux with Busybox, Micropython, zsh, less"

# bare-bones Linux and Busybox
[guest.riscv64-linux-busybox]
path = "boot/guests"
url = "https://github.com/diodesign/diosix/raw/binaries/buildroot-guests/riscv64-linux-busybox"
description = "64-bit RISC-V Linux with Busybox"

# select guests to include for a given target
[target.riscv64gc-unknown-none-elf]
guests = [ "riscv64-linux-busybox-micropython" ]

[target.riscv64imac-unknown-none-elf]
guests = [ "riscv64-linux-busybox-micropython" ]
