# Define the contents of a base system the hypervisor can boot
#
# This base system contains welcome banner(s), system services,
# and guests OSes that are bundled with the hypervisor binary
# and unpacked at run-time
#
# See src/mkdmfs/src/main.rs for the file format
#
# Directory paths are relative to this manifest.toml file

# these can be overridden by whatever's parsing this file, usually mkdmfs
[defaults]
arch = "riscv64gc-unknown-none-elf"
quality = "debug"
outfile = "src/mkdmfs/target/dmfs.img"

# define where to find the welcome banners
[banners]
path = "boot/banners"
welcome = "boot/banners/welcome.txt"

# define where to find the system services
[services]
path = "src/services"
include = [ "gooey" ]

# define any guests that may join us during boot
[guest.riscv64-linux-busybox]
path = "boot/guests"
url = "https://github.com/diodesign/diosix/raw/boot-binaries/boot/binaries/riscv64/supervisor"
description = "64-bit RISC-V Linux 5.4.58 with Busybox"

[guest.riscv32-linux-busybox]
path = "boot/guests"
url = "https://github.com/diodesign/diosix/raw/boot-binaries/boot/binaries/riscv32/supervisor"
description = "32-bit RISC-V Linux 5.4.61 with Busybox"

# select guests to include for a given target
[target.riscv64gc-unknown-none-elf]
guests = [ "riscv64-linux-busybox" ]

[target.riscv64imac-unknown-none-elf]
guests = [ "riscv64-linux-busybox" ]

[target.riscv32imac-unknown-none-elf]
guests = [ "riscv32-linux-busybox" ]