#!/usr/bin/env bash
# BuildRoot integration script for Diosix
#
# Usage: build_rootvm.sh <path_to_config> <path_to_output_binary> <path_to_buildroot_dir>

set -e

CONFIG_FILE="$1"
OUT_FILE="$2"
BUILDROOT_DIR="$3"
BUILDROOT_URL="https://gitlab.com/buildroot.org/buildroot.git"
BUILDROOT_BRANCH="2026.02.x"

if [ -z "$CONFIG_FILE" ] || [ -z "$OUT_FILE" ] || [ -z "$BUILDROOT_DIR" ]; then
    echo "Usage: $0 <config_file> <out_file> <buildroot_dir> [guest_arch]"
    exit 1
fi

GUEST_ARCH="${4:-riscv64}"
ROOTVM_S_PATH="$5"

HASH_FILE="${OUT_FILE}.sha256"
CURRENT_HASH=$(sha256sum "$CONFIG_FILE" "$0" $(dirname "$CONFIG_FILE")/*.fragment tools/diosix-ctl/src/*.zig tools/driver/diosix.c 2>/dev/null | sha256sum | cut -d' ' -f1)

write_rootvm_s() {
    if [ -n "$ROOTVM_S_PATH" ]; then
        ABS_OUT_FILE=$(realpath "$OUT_FILE")
        mkdir -p "$(dirname "$ROOTVM_S_PATH")"
        cat <<EOF > "$ROOTVM_S_PATH"
# Dynamically generated by build_rootvm.sh. DO NOT EDIT.
# Modification hash: $CURRENT_HASH
.section .rootvm, "a"
.global root_vm_start
.global root_vm_end
.balign 4096
root_vm_start:
.incbin "$ABS_OUT_FILE"
root_vm_end:
EOF
    fi
}

# Check if a rebuild is necessary using the configuration hash.
if [ -f "$OUT_FILE" ] && [ -f "$HASH_FILE" ]; then
    RECORDED_HASH=$(cat "$HASH_FILE")
    if [ "$CURRENT_HASH" = "$RECORDED_HASH" ]; then
        echo "Root VM binary is up to date. Skipping BuildRoot."
        write_rootvm_s
        exit 0
    fi
fi


echo "Root VM binary missing or outdated. Running BuildRoot..."
make -C "$BUILDROOT_DIR" linux-rebuild 2>/dev/null || true


# Get BuildRoot
if [ ! -d "$BUILDROOT_DIR/.git" ]; then
    echo "Cloning BuildRoot ($BUILDROOT_BRANCH) into $BUILDROOT_DIR..."
    TEMP_CLONE=$(mktemp -d -p "$(dirname "$BUILDROOT_DIR")")
    git clone --depth 1 -b "$BUILDROOT_BRANCH" "$BUILDROOT_URL" "$TEMP_CLONE"
    mv "$BUILDROOT_DIR/dl" "$TEMP_CLONE/dl" 2>/dev/null || true
    rm -rf "$BUILDROOT_DIR"
    mv "$TEMP_CLONE" "$BUILDROOT_DIR"
fi

# Compile diosix-ctl for target guest architecture and stage into overlay
mkdir -p tools/overlay-common/usr/sbin
rm -rf tools/overlay-common/sbin 2>/dev/null || true

ZIG_TARGET="${GUEST_ARCH}-linux-musl"
echo "Cross-compiling diosix-ctl for $ZIG_TARGET..."
zig build-exe tools/diosix-ctl/src/main.zig -target "$ZIG_TARGET" -O ReleaseSmall --name diosix-ctl -femit-bin=tools/overlay-common/usr/sbin/diosix-ctl



# Need to provide absolute path for defconfig if it's outside
ABS_CONFIG=$(realpath "$CONFIG_FILE")


# Configure BuildRoot, tracking version changes to trigger clean rebuilds
if [ -f "$BUILDROOT_DIR/.config" ]; then
    cp "$BUILDROOT_DIR/.config" "$BUILDROOT_DIR/.config.old"
fi

echo "Configuring BuildRoot..."
make -C "$BUILDROOT_DIR" BR2_DEFCONFIG="$ABS_CONFIG" defconfig

# Enforce the use of the appropriate console for the root login prompt
GETTY_PORT="hvc0"
if [ "$GUEST_ARCH" = "aarch64" ]; then
    GETTY_PORT="ttyAMA0"
elif [ "$GUEST_ARCH" = "x86_64" ]; then
    GETTY_PORT="ttyS0"
fi
echo "BR2_TARGET_GENERIC_GETTY_PORT=\"$GETTY_PORT\"" >> "$BUILDROOT_DIR/.config"

# Fixup step for modern buildroot: olddefconfig updates the config for new versions silently
make -C "$BUILDROOT_DIR" olddefconfig
make -C "$BUILDROOT_DIR" linux-dirclean 2>/dev/null || true

if [ -f "$BUILDROOT_DIR/.config.old" ]; then
    OLD_KV=$(grep -E '^BR2_LINUX_KERNEL_VERSION=' "$BUILDROOT_DIR/.config.old" | cut -d'"' -f2)
    NEW_KV=$(grep -E '^BR2_LINUX_KERNEL_VERSION=' "$BUILDROOT_DIR/.config" | cut -d'"' -f2)
    if [ "$OLD_KV" != "$NEW_KV" ] && [ -n "$OLD_KV" ]; then
        echo "Linux kernel version changed from '$OLD_KV' to '$NEW_KV'. Cleaning old kernel build..."
        make -C "$BUILDROOT_DIR" linux-dirclean linux-headers-dirclean
    fi
    rm "$BUILDROOT_DIR/.config.old"
fi

# Detect wget2 (e.g. Fedora 39+) which dropped --passive-ftp support.
# BuildRoot's download rules pass --passive-ftp by default and will fail
# if the system wget is actually wget2. Override BR2_WGET in that case.
WGET_EXTRA_ARGS=""
if wget --version 2>&1 | head -1 | grep -q "Wget2"; then
    echo "Detected wget2: overriding BR2_WGET to drop --passive-ftp..."
    WGET_EXTRA_ARGS='BR2_WGET="wget -nd -t 3"'
fi

# Inject diosix character driver into Linux kernel
echo "Preparing Linux kernel source tree..."
eval make -C "$BUILDROOT_DIR" linux-patch $WGET_EXTRA_ARGS 2>/dev/null || true
for linux_dir in "$BUILDROOT_DIR"/output/build/linux-*; do
    if [ -d "$linux_dir/drivers/char" ]; then
        echo "Injecting /dev/diosix driver into $linux_dir..."
        cp tools/driver/diosix.c "$linux_dir/drivers/char/diosix.c"
        if ! grep -q "diosix.o" "$linux_dir/drivers/char/Makefile"; then
            echo "obj-y += diosix.o" >> "$linux_dir/drivers/char/Makefile"
        fi
    fi
done

# Build it
echo "Building Root VM (this may take a while)..."
eval make -C "$BUILDROOT_DIR" -j"$(nproc)" $WGET_EXTRA_ARGS


# Ensure the output directory exists
mkdir -p "$(dirname "$OUT_FILE")"

# The output from a RISC-V buildroot Linux build with BR2_LINUX_KERNEL_VMLINUX=y is usually output/images/vmlinux
IMAGE_PATH="$BUILDROOT_DIR/output/images/vmlinux"
if [ ! -f "$IMAGE_PATH" ]; then
    echo "Error: BuildRoot finished but expected output image '$IMAGE_PATH' was not found!"
    exit 1
fi

echo "Copying built image to $OUT_FILE..."
cp "$IMAGE_PATH" "$OUT_FILE"
echo "$CURRENT_HASH" > "$HASH_FILE"

write_rootvm_s

echo "Root VM build complete!"



