# Dynamically generated by build_rootvm.sh. DO NOT EDIT.
# Modification hash: 1131aceb50565567cae387871ffc8aa41815dd4ca6cb2c60e17f1d5c4441c577
.section .rootvm, "a"
.global root_vm_start
.global root_vm_end
.balign 4096
root_vm_start:
.incbin "/home/chris/Documents/src/diosix-hq/diosix/zig-out/guest-riscv64/bin/rootvm.elf"
root_vm_end:
