name: Docker-based CI - Build and test Diosix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build test environment's Docker image
      run: docker build . --file Dockerfile --tag diosix:testenv
    - name: Run unit tests within Docker container
      run: docker run --rm -ti diosix:testenv
      
